# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 183655c5574324eed3abe6bc1412b3fbb21dc42880c5e5ce1d2ffc109b11577f984cbacfb353d7c38fb9366c7f10df6f69eb7d57191d799fd63dd040cb6927c7

test:
  secret_key_base: e5933e587b341a17a7a1101153e9f55bb89b4724bd3912fa40b8be34f96cd52d9613338297f7d8d12f151b00ec1aba8ffd71104b687d1c9db5194dcb685a4b19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
